title: Computational physics
description: A computational courses for anferivera's home page!
theme: just-the-docs

url: https://anferivera.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
